services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/khanh/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase
    ports:
      - 127.0.0.1:5432:5432


